# Generated by Django 4.2.6 on 2024-01-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers_otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transfer_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(default=12)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('amount', models.FloatField(default=0.0, null=True)),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_for_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
